---
abstract: 'a collection of Tickit::Widget implementations'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  Test::More: 0.88
dynamic_config: 1
generated_by: 'Module::Build version 0.4001, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tickit-Widgets
provides:
  Tickit::Widget::Border:
    file: lib/Tickit/Widget/Border.pm
    version: 0.08
  Tickit::Widget::Button:
    file: lib/Tickit/Widget/Button.pm
    version: 0.08
  Tickit::Widget::CheckButton:
    file: lib/Tickit/Widget/CheckButton.pm
    version: 0.08
  Tickit::Widget::Entry:
    file: lib/Tickit/Widget/Entry.pm
    version: 0.21
  Tickit::Widget::Frame:
    file: lib/Tickit/Widget/Frame.pm
    version: 0.26
  Tickit::Widget::GridBox:
    file: lib/Tickit/Widget/GridBox.pm
    version: 0.08
  Tickit::Widget::HSplit:
    file: lib/Tickit/Widget/HSplit.pm
    version: 0.08
  Tickit::Widget::LinearSplit:
    file: lib/Tickit/Widget/LinearSplit.pm
    version: 0.08
  Tickit::Widget::Placegrid:
    file: lib/Tickit/Widget/Placegrid.pm
    version: 0.08
  Tickit::Widget::RadioButton:
    file: lib/Tickit/Widget/RadioButton.pm
    version: 0.08
  Tickit::Widget::VSplit:
    file: lib/Tickit/Widget/VSplit.pm
    version: 0.08
  Tickit::Widgets:
    file: lib/Tickit/Widgets.pm
    version: 0.08
requires:
  Tickit::RenderContext: 0.07
  Tickit::Style: 0.32
  Tickit::Utils: 0.29
  Tickit::Widget: 0.30
resources:
  license: http://dev.perl.org/licenses/
version: 0.08
